Support device control from LIFF
line/line-things-dev-board pull request #6
Opened 2019-05-10 09:15 UTC by cpulabs

1, Added new device control mechanism from LIFF
2, support version information

Added new characteristic to allow LIFF to control the device.
This is not require firmware change. Possible to read, write, and notify execution control from the LIFF side.

2019-05-15 05:32 UTC, techno commented on README.md
> +## デフォルトファームウェアのUUIDを変更して書き込んだが古いUUIDのまま変わらない
古いデバイスの連携解除が必要かも

2019-05-15 05:33 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> +#define USER_CHARACTERISTIC_NOTIFY_UUID "e90b4b4e-f18a-44f0-8691-b041c7fe57f2"
ここまで拡張すると、`USER_SERVICE`, `USER_CHARACTERISTIC` とはわかりにくい (Starter が元になっているだけ) ので、名前を適切な名前に変えたほうがいい。

2019-05-15 05:44 UTC, hktechn0 requested changes
全体的に Conding Style が統一されていない。
無駄な空行、`method(){` (スペースがない)、

2019-05-15 05:44 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> +#define USER_CHARACTERISTIC_NOTIFY_UUID "e90b4b4e-f18a-44f0-8691-b041c7fe57f2"
ここまで拡張すると、USER_SERVICE, USER_CHARACTERISTIC とはわかりにくい (Starter が元になっているだけ) ので、名前を適切な名前に変えたほうがいい。

2019-05-15 05:44 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> +#define USER_DEBUG        //Debugを無効にするにはコメントアウトを外す
Debug Off が default

2019-05-15 05:44 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> + * このファームウェアは2種類の動作モードがあります。
コード内コメントは英語で書いてほしい

2019-05-15 05:44 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> +	blesv_devboard_version.setPermission(SECMODE_ENC_NO_MITM, SECMODE_ENC_NO_MITM);
indentation

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/default/liff-starter.js
> +const USER_SERVICE_UUID = "f2b742dc-35e3-4e55-9def-0ce4a209c552";
ここの Service UUID の名前も意味がわかりにくい

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/js-framework.js
> +class ThingsConn {
もっと適切な名前

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/js-framework.js
> +class ThingsConn {
コード内にも使い方や、Doc comment が必要

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/js-framework.js
> +        onScreenLog('Read Value  : ' + result[0] + ", " + result[1]);
`onScreenLog()` 箱のファイルに存在しないので使うべきではない。
console.log または、出力しない

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/js-framework.js
> +            flashSDKError(e);
flashSDKError も同様にここで使うべきではない

2019-05-15 05:44 UTC, techno commented on arduino/linethings-dev-default/linethings-dev-default.ino
> + * Write to device format
この説明を README にも書くか、README をコード内から参照させる

2019-05-15 05:44 UTC, techno commented on liff-app/js-control/default/liff-starter.js
> +        ).catch(e => `ERROR on displayControl(): ${e}\n${e.stack}`);
ここ全てエラー表示のための `onScreenLog` が抜けてる

2019-05-15 05:44 UTC, techno commented
`liff-starter.js` は、starter ではないので名前を変えるべき

2019-05-17 05:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/line/line-things-dev-board?pullRequest=6) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/line/line-things-dev-board?pullRequest=6) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: cpulabs<br/>:x: techno<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/line/line-things-dev-board?pullRequest=6) it.</sub>

2019-05-21 05:16 UTC, hktechn0 approved these changes

2019-05-21 05:21 UTC, merged